[package]
name = "capnproto-rpc-echo"
version = "0.1.0"
authors = ["Kevin Warrick <kevinjwarrick@gmail.com>"]
edition = "2018"

[build-dependencies]
capnpc = "0.9.3"

[dependencies]
capnp = "0.9.4"
capnp-rpc = "0.9.0"
tokio = "0.1.15"
